### ISSUE TITLE
ERROR:  could not open extension control file "/usr/share/postgresql/9.4/extension/postgis.control": No such file or directory

### ISSUE THREAD

**Issue by ubergesundheit** [md5/docker-postgis#5]
Hi,

I tried to run `CREATE EXTENSION postgis;` on the image `mdillon/postgis:9.4` from the docker hub. It complained that it couldn't find the file `/usr/share/postgresql/9.4/extension/postgis.control`

running bash inside the container reveals that in fact this file exists!

I already tried the following things:
- building from this repository
- changing ownership of `/usr/share/postgresql/9.4/extension/` to the `postgres` user (`RUN chown -R postgres:postgres /usr/share/postgresql/9.4/extension/`)

Could you please look into this?

Cheers

**Comment by md5** [comment]
How did you run the `CREATE EXTENSION` statement? Did you connect to the container with `psql` or something else?

**Comment by ubergesundheit** [comment]
I am using fig (http://fig.sh) for running a ruby on rails app which uses postgis. When I am running `fig run app rake db:migrate` rails tries to create the posgis extension with `CREATE EXTENSION postgis;` which then fails.

**Comment by md5** [comment]
I just tested this successfully:

    $ docker pull mdillon/postgis:9.4
    # Time passes...
    $ docker run -d --name some-postgis -e POSTGRES_PASSWORD=p mdillon/postgis:9.4
    4825867790a1583c8bd9c58498ed876197795166855c513fca501d7c78a53f83
    $ docker run -it --link some-postgis:postgres --rm postgres \
       sh -c 'exec env PGPASSWORD="$POSTGRES_ENV_POSTGRES_PASSWORD" \
                 psql -h "$POSTGRES_PORT_5432_TCP_ADDR" 
                         -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres'
    psql (9.4.0, server 9.4.1)
    Type "help" for help.
    postgres=# create database postgis;
    CREATE DATABASE
    postgres=# \c postgis
    psql (9.4.0, server 9.4.1)
    You are now connected to database "postgis" as user "postgres".
    postgis=# create extension postgis;
    CREATE EXTENSION

**Comment by md5** [comment]
Can you post your `fig.yml`? It might also be relevant to find out what version of Fig you're using, but probably not.

**Comment by ubergesundheit** [comment]
`fig --version` returns `fig 1.0.0`

my fig.yml is
```yml
db:
  image: mdillon/postgis:9.4
  ports:
    - "5432"
  environment:
    - POSTGRES_PASSWORD=yoloswag

app:
  build: .
  links:
    - db
  environment:
    - RAILS_ENV=production
    - DEVISE_SECRET_KEY=swaghettiYolonaise
    - SECRET_KEY_BASE=swaghettiYolonaise
    - OAUTH_FACEBOOK_KEY=swaghettiYolonaise
    - OAUTH_FACEBOOK_SECRET=swaghettiYolonaise
    - OAUTH_TWITTER_KEY=swaghettiYolonaise
    - OAUTH_TWITTER_SECRET=swaghettiYolonaise
    - OAUTH_GOOGLE_KEY=swaghettiYolonaise
    - OAUTH_GOOGLE_SECRET=swaghettiYolonaise
    - HOSTNAME=localhost:3000
    - SMTP_HOST=smtp.mandrillapp.com
    - SMTP_PORT=25
    - SMTP_USER=SOMEUSER
    - SMTP_PASSWORD=SOMEPASS
    - EMAIL_FROM=some-email@provider.com
    - SENTRY_DSN=http://localhost
```

the dockerfile for the `app` installs `postgresql-client`
